Vagrant.configure("2") do |config|
  config.vm.box = "cheretbe/docker-tests"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
  end
  config.vm.synced_folder "../../..", "/ao-env"
end
