Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    # vb.customize ["sharedfolder", "add", :id, "--name", "ao-env",
    #   "--hostpath", File.expand_path("../../..", File.dirname(__FILE__)), "--automount"]
  end
  config.vm.synced_folder "../../..", "/ao-env"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provision/provision.yml"
    ansible.compatibility_mode = "2.0"
    ansible.extra_vars = {
      "ansible_python_interpreter": "/usr/bin/python3"
    }
  end
end
